name: Build and publish Linux package builder images
on:
  push:
    tags:
      - 'pkg-build-*'
    paths:
      - 'anaconda-pkg-build/linux/Dockerfile'
      - '.github/workflows/anaconda_pkg_build_linux.yml'
  pull_request:
    paths:
      - 'anaconda-pkg-build/linux/Dockerfile'
      - '.github/workflows/anaconda_pkg_build_linux.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Login to DockerHub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Public ECR
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: |
            continuumio/anaconda-pkg-build
            public.ecr.aws/y0o4y9o3/anaconda-pkg-build
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=pkg-build-(.*),group=1

      - name: build-push pkg-builder
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: ./anaconda-pkg-build/linux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda-pkg-build/linux/Dockerfile
          platforms: linux/amd64,linux/ppc64le,linux/arm64/v8,linux/s390x
          build-args: |
            BASEVERSION=7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}

      - name: Docker meta for Concourse
        id: concourse-meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: |
            continuumio/anaconda-pkg-build
            public.ecr.aws/y0o4y9o3/anaconda-pkg-build
          tags: |
            type=ref,event=branch,suffix=-amd64
            type=ref,event=pr,suffix=-amd64
            type=match,pattern=pkg-build-(.*),group=1,suffix=-amd64
          flavor: |
            latest=false

      - name: build-push pkg-builder-concourse
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: ./anaconda-pkg-build/linux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda-pkg-build/linux/Dockerfile
          platforms: linux/amd64
          build-args: |
            BASEVERSION=7
          tags: ${{ steps.concourse-meta.outputs.tags }}
          labels: ${{ steps.concourse-meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
