name: Build Miniconda3 Alpine Image
on:
  push:
    tags:
      - 'miniconda3-v*.*.*-alpine'
    paths:
      - 'miniconda3/alpine/Dockerfile'
      - '.github/workflows/miniconda_alpine_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/alpine/Dockerfile'
      - '.github/workflows/miniconda_alpine_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Login to DockerHub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@12cce9efe0d49980455aaaca9b071c0befcdd702
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch,suffix=-alpine
            type=ref,event=pr,suffix=-alpine
            type=match,pattern=miniconda3-v(.*)-alpine,group=1,suffix=-alpine
          flavor: |
            latest=false

      - name: build miniconda3/alpine
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          context: ./miniconda3/alpine
          builder: ${{ steps.buildx.outputs.name }}
          file: ./miniconda3/alpine/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
